import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/component/navbar/Navbar'
import Footer from '@/component/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'create next app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <br/>
        <Footer/>
        </body>
    </html>
  )
}
